# Project information

site_name: Research Workshops
site_description: 'A collection of AWS Research related workshops'
site_author: 'aws-research-workshops@amazon.com'
site_url: 'https://awsresearchworkshops.com'

# Repository
repo_name: 'aws-samples/aws-research-workshops'
repo_url: 'https://github.com/aws-samples/aws-research-workshops'

# Copyright
copyright: '&copy; 2018, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
# extra_css:
#   - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awsresearchworkshops.com'
    - type: 'globe'
      link: 'https://aws.amazon.com/government-education/research-and-technical-computing/'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/publicsector/tag/research/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Home: 'index.md'
  - Getting Started: 'getting-started.md'
  - Workshops: 
    - 'Directory': 'workshops/index.md'
    - 'Introduction to AWS Basics': 
      - 'Overview': 'workshops/basics/index.md'
    - 'Buidling a Data Lake for Analytics and Machine Learning': 
      - 'Overview': 'workshops/data-lake/index.md'
    - 'Build, Train, and Deploy ML Models at scale with Amazon SagaeMaker': 
      - 'Overview': 'workshops/ml-intro/index.md'
    - 'Build Serverless Applications in Python with AWS SAM CLI': 
      - 'Overview': 'workshops/serverless/index.md'
    - 'Tensorflow with Amazon SageMaker': 
      - 'Overview': 'workshops/ml-tensorflow/index.md'
    - 'Introduction to IoT Greengrass': 
      - 'Overview': 'workshops/greengrass/index.md'
    - 'Cost-effective Research leveraging AWS Spot': 
      - 'Overview': 'workshops/spot/index.md'
    - 'Build a Genomics Pipeline on AWS with Cromwell and AWS Batch': 
      - 'Overview': 'workshops/genomics/index.md'                        
  - Contributing: 'contribute.md'
  - License: 'license.md'