Description: " Creates resources (IAM role and SageMaker Notebook instance) for the Research Workshops"
Parameters:
  NotebookInstanceType:
    Type: "String"
    Default: ml.t2.medium
    AllowedValues:
      - ml.t2.medium
      - ml.t2.large
      - ml.t2.xlarge
      - ml.t2.2xlarge
      - ml.m4.xlarge
      - ml.m4.2xlarge
      - ml.p2.xlarge
      - ml.p3.2xlarge
    Description: Enter a valid SageMaker notebook instance type. Defaults to ml.t2.medium.

  UserName:
    Type: String
    Description: Name of the Workshop User
    Default: WorkshopUser

  IAMUserPassword:
    Description: IAM User Password used for the workshop user.
    Type: String
    NoEcho: True
    
Resources:
  SageMakerResearchIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [
                "sagemaker.amazonaws.com",
                "glue.amazonaws.com"
            ]
            Action: "sts:AssumeRole"
      Path: "/service-role/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

  ResearchNotebookLifecycleConfig: 
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties: 
      OnStart: 
        - Content:
            Fn::Base64: !Sub |       
                #!/bin/bash
                set -e
                sudo -i -u ec2-user bash << EOF
                echo "Setup the Workshop exercises"
                git clone https://github.com/aws-samples/aws-research-workshops ~/SageMaker/aws-research-workshops/

  SageMakerNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      NotebookInstanceName: !Sub ${UserName}-Workshop-Notebook
      InstanceType: !Ref NotebookInstanceType
      RoleArn: !GetAtt SageMakerResearchIAMRole.Arn
      LifecycleConfigName: !GetAtt ResearchNotebookLifecycleConfig.NotebookInstanceLifecycleConfigName

  WorkshopUser:
    Type: "AWS::IAM::User"
    Properties: 
      LoginProfile:
        Password: !Ref IAMUserPassword
      UserName: !Ref UserName
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/ReadOnlyAccess
          
  WorkshopPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Sid: WorkshopAccess
          Effect: Allow
          Action: [        
              'sagemaker:Start*',
              'sagemaker:Stop*',
              'sagemaker:CreatePresignedNotebookInstanceUrl'
          ]
          Resource: [
              !Ref SageMakerNotebookInstance 
          ]
          Condition:
              StringEquals:
                aws:RequestedRegion: ${AWS::Region}
        - Sid: WorkshopListAccess
          Effect: Allow
          Action: [        
              'sagemaker:List*',
              'sagemaker:Describe*'
          ]
          Resource: "*"
          Condition:
              StringEquals:
                aws:RequestedRegion: ${AWS::Region}
        - Sid: WorkshopBatchAccess
          Effect: Allow
          Action: [        
              'batch:SubmitJob'
          ]
          Resource: "*"
          Condition:
              StringEquals:
                aws:RequestedRegion: ${AWS::Region}
      PolicyName: !Sub ${UserName}-WorkshopPolicy
      Users:
        - !Ref UserName
    DependsOn: WorkshopUser 
    
Outputs:
  SageMakerNotebookInstance:
    Value: !GetAtt SageMakerNotebookInstance.NotebookInstanceName
  
  IAMRole:
    Value: !GetAtt SageMakerResearchIAMRole.Arn

  OpenInstanceLink:
    Value: !Sub
      - https://${NotebookInstanceName}.notebook.${AWS::Region}.sagemaker.aws/tree
      - { NotebookInstanceName: !GetAtt SageMakerNotebookInstance.NotebookInstanceName }