---
AWSTemplateFormatVersion: '2010-09-09'
Description: Greengrass EC2 instance

Parameters:

  InstanceType:
    Description: Greengrass EC2 Instance
    Type: String
    Default: m4.large
    AllowedValues: [m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge]
    ConstraintDescription: must be a valid EC2 instance type.

  Subnet:
    Description: Choose a Subnet to deploy the Instance
    Type: AWS::EC2::Subnet::Id

  S3BucketName: 
    Description: Bucket used for the workshop
    Type: String

  ImageId:
    Description: AMI name
    Type: String
    Default: sg-02f5ebe0fb3be07f1

  SG:
    Description: Choose a SecurityGroupId
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  ggdEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
#       KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref Subnet
      SecurityGroupIds: 
        - !Ref SG
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
                      #!/bin/bash
                      sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm

                      echo LANG=en_US.utf-8 >> /etc/environment
                      echo LC_ALL=en_US.UTF-8 >> /etc/environment

                      if ! uname -r |grep amzn ; then
                          exit 1
                      fi

                      cd /tmp/
                      wget https://d1onfpft10uf5o.cloudfront.net/greengrass-core/downloads/1.7.0/greengrass-linux-x86-64-1.7.0.tar.gz

                      tar zxf /tmp/greengrass-linux-x86-64-1.7.0.tar.gz -C /

                      cp /tmp/root.ca.pem /greengrass/certs/
                      useradd -r ggc_user
                      groupadd -r ggc_group

                      echo 'fs.protected_hardlinks = 1' >> /etc/sysctl.d/00-defaults.conf
                      echo 'fs.protected_symlinks = 1' >> /etc/sysctl.d/00-defaults.conf

                      sysctl -p
                      sysctl -p /etc/sysctl.d/00-defaults.conf

                      echo '# AWS Greengrass' >> /etc/fstab
                      echo 'cgroup /sys/fs/cgroup cgroup defaults 0 0' >> /etc/fstab
                      mount -a

                      yum -y install sqlite telnet jq strace git tree

                      PATH=$PATH:/usr/local/bin
                      pip install --upgrade pip
                      hash -r
                      pip install AWSIoTPythonSDK
                      pip install urllib3
                      pip install --upgrade awscli
                      pip install boto3
                      pip install fire
                      pip install gg-group-setup

                      mkdir -p /health/groups/
                      cd /health/groups/
                      aws s3 cp s3://${S3BucketName}/device/tracker.zip .
                      unzip tracker.zip
                      cd /health/groups/tracker/
                      
                      chmod 755 cp_certs.sh start_tracker.sh stop_tracker.sh

                      ./cp_certs.sh
                      
                      cp /health/groups/tracker/gg_config.json /greengrass/config/config.json
                      
                      chmod 755 /health/groups/tracker/*.sh

                      exit 0

      Tags:
        - Key: Name
          Value: GGDSessionManager

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles:
        - !Ref EC2Role 
      InstanceProfileName: EC2InstanceProfile

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2RoleForSessionManager
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"

Outputs:
    EC2InstanceId:
        Description: The Greengrass device instance id
        Value: !Ref ggdEC2Instance